@startuml

component core {
	package wishList.core
	package wishList.json
}

wishList.core ..> wishList.json
component jackson {
}

wishList.json ..> jackson



component fxui {
	package wishList.ui
}


wishList.ui ..> wishList.core
wishList.ui ..> wishList.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml


@enduml
