@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "wishList.core.User#User(String,String,String,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "wishList.core.User"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3059615 { 
   	label=core
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1660553199 { 
   	label=User
	labeljust=l
	fillcolor=white
	style=filled
   
   User1394157064XXXUser2012146208[
	label="+ User()"
	style=filled
	fillcolor=white
	tooltip="User

&#10;  Create user with firstname, lastname, email and password.&#10; &#10;  @param firstName firstname&#10;  @param lastName lastname&#10;  @param email email&#10;  @param password password&#10;  @throws IllegalArgumentException if first or lastname don't match with constraints&#10; "
	penwidth=4
	fontcolor=darkgreen
];

User1394157064XXXsetFirstName1808118735[
	label="+ setFirstName()"
	style=filled
	fillcolor=white
	tooltip="User

&#10;  Set firstname of user.&#10; &#10;  @param firstName name&#10;  @return user object&#10;  @throws IllegalArgumentException if name is not sufficient.&#10; "
	fontcolor=darkgreen
];

User1394157064XXXsetLastName1808118735[
	label="+ setLastName()"
	style=filled
	fillcolor=white
	tooltip="User

&#10;  Set lastname of user.&#10; &#10;  @param lastName name&#10;  @return User object&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3271912 { 
   	label=json
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1309376005 { 
   	label=JsonHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   JsonHandler1394369361XXXaddUser2012146208[
	label="+ addUser()"
	style=filled
	fillcolor=white
	tooltip="JsonHandler

&#10;  Add user to users.wishList.json if it has a unique email&#10; &#10;  @param firstname firstname&#10;  @param lastname lastname&#10;  @param email email&#10;  @param password password&#10;  @return user created&#10;  @throws IllegalArgumentException if email is not unique&#10;  @throws Exception if not found file&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_522399067 { 
   	label=UserDeserializer
	labeljust=l
	fillcolor=white
	style=filled
   
   UserDeserializer1394369361XXXdeserialize1802127749[
	label="+ deserialize()"
	style=filled
	fillcolor=white
	tooltip="UserDeserializer

&#10;  Deserialize user object from wishList.json.&#10; &#10;  @param jsonParser what parser we use&#10;  @param deserializationContext context&#10;  @return user object&#10;  @throws IOException file not found&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3732 { 
   	label=ui
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2033919893 { 
   	label=RegisterViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   RegisterViewController1531507907XXXregisterUser1067311644[
	label="+ registerUser()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Sign up user.&#10; &#10;  @param event gets state&#10; "
	fontcolor=darkgreen
];
} 
} 

'edges    
JsonHandler1394369361XXXaddUser2012146208 -> User1394157064XXXUser2012146208;
RegisterViewController1531507907XXXregisterUser1067311644 -> JsonHandler1394369361XXXaddUser2012146208;
User1394157064XXXUser2012146208 -> User1394157064XXXsetFirstName1808118735;
User1394157064XXXUser2012146208 -> User1394157064XXXsetLastName1808118735;
UserDeserializer1394369361XXXdeserialize1802127749 -> User1394157064XXXUser2012146208;
    
}
@enduml