@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "wishList.core.User#checkCredentials(String,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "wishList.core.User"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3059615 { 
   	label=core
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1660553199 { 
   	label=User
	labeljust=l
	fillcolor=white
	style=filled
   
   User1394157064XXXcheckCredentials2013066710[
	label="+ checkCredentials()"
	style=filled
	fillcolor=white
	tooltip="User

&#10;  Checks to see if user's email and passwords match with inputs.&#10; &#10;  @param email email string&#10;  @param password password string&#10;  @return boolean&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3271912 { 
   	label=json
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1309376005 { 
   	label=JsonHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   JsonHandler1394369361XXXloadUser2013066710[
	label="+ loadUser()"
	style=filled
	fillcolor=white
	tooltip="JsonHandler

&#10;  Load user with given email and password.&#10; &#10;  @param email email of user&#10;  @param password password of user&#10;  @return user if he exists&#10;  @throws Exception could not load file.&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3732 { 
   	label=ui
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_989227111 { 
   	label=LoginViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   LoginViewController1531507907XXXchangeToMainView1067311644[
	label="+ changeToMainView()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

&#10;  Change scene to MainView.fxml Will only change scene if e-mail and password match&#10; &#10;  @param event event when clicking&#10;  @throws IOException file not found&#10; "
	fontcolor=darkgreen
];
} 
} 

'edges    
JsonHandler1394369361XXXloadUser2013066710 -> User1394157064XXXcheckCredentials2013066710;
LoginViewController1531507907XXXchangeToMainView1067311644 -> JsonHandler1394369361XXXloadUser2013066710;
    
}
@enduml