@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "wishList.core.User#getFirstName()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "wishList.core.User"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3059615 { 
   	label=core
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1660553199 { 
   	label=User
	labeljust=l
	fillcolor=white
	style=filled
   
   User1394157064XXXgetFirstName0[
	label="+ getFirstName()"
	style=filled
	fillcolor=white
	tooltip="User

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3271912 { 
   	label=json
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1281396762 { 
   	label=UserSerializer
	labeljust=l
	fillcolor=white
	style=filled
   
   UserSerializer1394369361XXXserialize737447261[
	label="+ serialize()"
	style=filled
	fillcolor=white
	tooltip="UserSerializer

&#10;  Serialize user.&#10; &#10;  @param user user to be serialized&#10;  @param jsonGenerator jsonGenerator to be used&#10;  @param serializerProvider provider&#10;  @throws IOException if file to serializer user to is not found&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3732 { 
   	label=ui
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1108789293 { 
   	label=ShowListViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   ShowListViewController1531507907XXXchangeToLoginView1067311644[
	label="+ changeToLoginView()"
	style=filled
	fillcolor=white
	tooltip="ShowListViewController

&#10;  Change scene to LoginView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

ShowListViewController1531507907XXXchangeToMainView1067311644[
	label="+ changeToMainView()"
	style=filled
	fillcolor=white
	tooltip="ShowListViewController

&#10;  Change scene to MainView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

ShowListViewController1531507907XXXchangeToRegisterView1067311644[
	label="+ changeToRegisterView()"
	style=filled
	fillcolor=white
	tooltip="ShowListViewController

&#10;  Change scene to RegisterView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

ShowListViewController1531507907XXXchangeToShowListView1067311644[
	label="+ changeToShowListView()"
	style=filled
	fillcolor=white
	tooltip="ShowListViewController

&#10;  Change scene to ShowListView.&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1776582485 { 
   	label=MainViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   MainViewController1531507907XXXchangeToLoginView1067311644[
	label="+ changeToLoginView()"
	style=filled
	fillcolor=white
	tooltip="MainViewController

&#10;  Change scene to LoginView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

MainViewController1531507907XXXchangeToMainView1067311644[
	label="+ changeToMainView()"
	style=filled
	fillcolor=white
	tooltip="MainViewController

&#10;  Change scene to MainView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if the file is not found&#10; "
	fontcolor=darkgreen
];

MainViewController1531507907XXXchangeToRegisterView1067311644[
	label="+ changeToRegisterView()"
	style=filled
	fillcolor=white
	tooltip="MainViewController

&#10;  Change scene to RegisterView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if the file is not found&#10; "
	fontcolor=darkgreen
];

MainViewController1531507907XXXchangeToShowListView1067311644[
	label="+ changeToShowListView()"
	style=filled
	fillcolor=white
	tooltip="MainViewController

&#10;  Change scene to ShowListView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

MainViewController1531507907XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="MainViewController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2033919893 { 
   	label=RegisterViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   RegisterViewController1531507907XXXchangeToLoginView1067311644[
	label="+ changeToLoginView()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Change scene to LoginView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

RegisterViewController1531507907XXXchangeToMainView1067311644[
	label="+ changeToMainView()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Change scene to MainView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

RegisterViewController1531507907XXXchangeToRegisterView1067311644[
	label="+ changeToRegisterView()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Change scene to RegisterView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

RegisterViewController1531507907XXXchangeToShowListView1067311644[
	label="+ changeToShowListView()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Change scene to ShowListView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

RegisterViewController1531507907XXXregisterUser1067311644[
	label="+ registerUser()"
	style=filled
	fillcolor=white
	tooltip="RegisterViewController

&#10;  Sign up user.&#10; &#10;  @param event gets state&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_989227111 { 
   	label=LoginViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   LoginViewController1531507907XXXchangeToLoginView1067311644[
	label="+ changeToLoginView()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

&#10;  Change scene to LoginView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

LoginViewController1531507907XXXchangeToMainView1067311644[
	label="+ changeToMainView()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

&#10;  Change scene to MainView.fxml Will only change scene if e-mail and password match&#10; &#10;  @param event event when clicking&#10;  @throws IOException file not found&#10; "
	fontcolor=darkgreen
];

LoginViewController1531507907XXXchangeToRegisterView1067311644[
	label="+ changeToRegisterView()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

&#10;  Change scene to RegisterView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];

LoginViewController1531507907XXXchangeToShowListView1067311644[
	label="+ changeToShowListView()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

&#10;  Change scene to ShowListView.fxml&#10; &#10;  @param event gets state&#10;  @throws IOException if file is not found&#10; "
	fontcolor=darkgreen
];
} 
} 

'edges    
LoginViewController1531507907XXXchangeToLoginView1067311644 -> MainViewController1531507907XXXinitialize0;
LoginViewController1531507907XXXchangeToMainView1067311644 -> MainViewController1531507907XXXinitialize0;
LoginViewController1531507907XXXchangeToRegisterView1067311644 -> MainViewController1531507907XXXinitialize0;
LoginViewController1531507907XXXchangeToShowListView1067311644 -> MainViewController1531507907XXXinitialize0;
MainViewController1531507907XXXchangeToLoginView1067311644 -> MainViewController1531507907XXXinitialize0;
MainViewController1531507907XXXchangeToMainView1067311644 -> MainViewController1531507907XXXinitialize0;
MainViewController1531507907XXXchangeToRegisterView1067311644 -> MainViewController1531507907XXXinitialize0;
MainViewController1531507907XXXchangeToShowListView1067311644 -> MainViewController1531507907XXXinitialize0;
MainViewController1531507907XXXinitialize0 -> User1394157064XXXgetFirstName0;
RegisterViewController1531507907XXXchangeToLoginView1067311644 -> MainViewController1531507907XXXinitialize0;
RegisterViewController1531507907XXXchangeToMainView1067311644 -> MainViewController1531507907XXXinitialize0;
RegisterViewController1531507907XXXchangeToRegisterView1067311644 -> MainViewController1531507907XXXinitialize0;
RegisterViewController1531507907XXXchangeToShowListView1067311644 -> MainViewController1531507907XXXinitialize0;
RegisterViewController1531507907XXXregisterUser1067311644 -> RegisterViewController1531507907XXXchangeToMainView1067311644;
ShowListViewController1531507907XXXchangeToLoginView1067311644 -> MainViewController1531507907XXXinitialize0;
ShowListViewController1531507907XXXchangeToMainView1067311644 -> MainViewController1531507907XXXinitialize0;
ShowListViewController1531507907XXXchangeToRegisterView1067311644 -> MainViewController1531507907XXXinitialize0;
ShowListViewController1531507907XXXchangeToShowListView1067311644 -> MainViewController1531507907XXXinitialize0;
UserSerializer1394369361XXXserialize737447261 -> User1394157064XXXgetFirstName0;
    
}
@enduml